spring:
  application:
    name: backend

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/mydb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true

  servlet:
    encoding:
      charset: UTF-8
      force-response: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

server:
  servlet:
    session:
      cookie:
        http-only: true
        same-site: lax

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.backend.backend
  configuration:
    map-underscore-to-camel-case: true
