spring:
  application:
    name: backend

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/mydb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.backend.backend
  configuration:
    map-underscore-to-camel-case: true
